HOSTS:
  ubuntu-1404-controller:
    roles:
      - controller
      - default
    platform: ubuntu-1404-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant
    vagrant_memsize: 2048
  ubuntu-1404-node:
    roles:
      - node
    platform: ubuntu-1404-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
  trace_limit: 200
